name: Deploy pro

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH Super Debug qadami
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          echo "--- SSH ULANISH JARAYONINI KUZATAMIZ ---"
          # -vvv bayrog'i server nima uchun javob bermayotganini fosh qiladi
          ssh -vvv -o StrictHostKeyChecking=no dev@169.58.30.176 "echo 'TEST-SUCCESS' && whoami"